export const FETCH_DATA_NEW_ARTISTS = "FETCH_DATA_NEW_ARTISTS";
export const FETCH_DATA_NEW_GIGS = "FETCH_DATA_NEW_GIGS";
export const FETCH_DATA_SEARCH_ARTISTS = "FETCH_DATA_SEARCH_ARTISTS";
export const FETCH_DATA_SEARCH_GIGS = "FETCH_DATA_SEARCH_GIGS";
